name: ARTIFACT

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install
        run: npm install
      - name: npm build
        run: npm build
      - name: ls
        run: ls
      # - name: Archive production artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Build
      #     path: |
      #       dist
      #       !dist/**/*.md